name: commit_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: abystoma/checkout@v1
        with:
          repository: https://github.com/abystoma/external-workflow
          ref: 3eb718710f20d7df6874acdc41e189a2ae4182f5
      - name: Greetings
        run: echo "$(<greeting.txt)"